#!/bin/sh
#
# @author Markus Raab <elektra@markus-raab.org>
# @brief Configure a debian wheezy build
# @date 30.10.2014
# @tags configure, debian, wheezy

. "$(dirname "$0")/configure-common"

cd $BUILD
cmake	-DPLUGINS="ALL" \
	-DTOOLS="ALL" \
	-DBINDINGS="cpp;swig_python2;swig_python;jna" \
	$*
