#!/bin/sh
#
# @author Markus Raab <elektra@markus-raab.org>
# @brief Configuration to use XDG as the default resolver
# @date 10.11.2014
# @tags configure, xdg, resolver

. "$(dirname "$0")/configure-common"

XDG_RESOLVER="resolver_mf_xp_x"

cd $BUILD
cmake	-DPLUGINS="$XDG_RESOLVER;dump;sync;error" \
	-DKDB_DEFAULT_RESOLVER="$XDG_RESOLVER" \
	$*
