#!/bin/sh
#
# @author Markus Raab <elektra@markus-raab.org>
# @brief Configuration script for configuration stored in .ini format.
# @date 16.02.2016
# @tags configure, ini

. "$(dirname "$0")/configure-common"

cd $BUILD
cmake	-DSWIG_EXECUTABLE=/usr/bin/swig3.0 \
	-DKDB_DB_FILE="default.ini" \
	-DKDB_DB_INIT="elektra.ini" \
	-DKDB_DEFAULT_STORAGE="ini" \
	-DPLUGINS="ALL" \
	-DTOOLS="ALL" \
	-DBINDINGS="ALL" \
	$*
